Added currency symbols RUB and TMT
gb-converter/parser pull request #23
Opened 2020-12-03 09:38 UTC by monstric93

2020-12-03 12:53 UTC, gb-converter requested changes
Думаю нужно добавить комментарий в том местре где мы связваем код валюты 934 с Символом валюты.

2020-12-03 12:53 UTC, gb-converter commented on main.py
> +                if num_code == 934:
Выглядит как временное решение. Думаю нужно добавить комментарий о том с какой валютой связан данный символ (ведь по истечение некоторого времени этой валюты может не остаться либо она. может "трансформироваться)

2020-12-04 17:50 UTC, monstric93 commented
Комментарий добавлен к строчкам кода

2020-12-05 16:53 UTC, viktor-filinskij approved these changes

2020-12-05 16:53 UTC, gb-converter approved these changes

2020-12-05 16:58 UTC, merged